import { Inter } from "next/font/google";
import "/public/globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DO's BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
            <div className="navbar">
              <Link href="/">홈</Link>
              <Link href="/list">List 13</Link>
            </div>
            {children}
      </body>
    </html>
  );
}
