import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DO's BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
            <div className="navbar">
              <p><Link href="/" style={{ display: 'block', marginBottom: '10px', color: '#ffffff' }}>HOME</Link></p>
              <p><Link href="/skills" style={{ display: 'block', marginBottom: '10px', color: '#ffffff' }}>SKILLS</Link></p>
              <p><Link href="/posts" style={{ display: 'block', marginBottom: '10px', color: '#ffffff' }}>POSTS</Link></p>
            </div>
            {children}
      </body>
    </html>
  );
}
